config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'

  resources :notes, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :memos, only: [:create, :destroy]
  end

  resources :book_marks, only: [:index, :create, :show, :update, :destroy]
  resources :book_mark_details, only: [:create, :destroy]
  resource :user, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
  belongs_to :user
  has_many :book_mark_details, dependent: :destroy

  validates :name, presence: true
end

app/models/book_mark_detail.rb
class BookMarkDetail < ApplicationRecord
  belongs_to :note
  belongs_to :book_mark

  validates :note_id, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :memo, presence: true
  validates :user_id, presence: true
  validates :note_id, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :book_mark_details, dependent: :destroy

  validates :opinion, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :book_marks, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    notes_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/book_mark_details_controller.rb
class BookMarkDetailsController < ApplicationController

  def create
    @book_mark_detail = BookMarkDetail.new(book_mark_detail_params)
    if @book_mark_detail.save
      redirect_to book_mark_path(@book_mark_detail.book_mark.id)
    else
      @note = Note.find(params[:id])
      @memo = Memo.new
      @memos = current_user.memos.all
      @book_marks = current_user.book_marks.all
      @book_mark_detail = BookMarkDetail.new
      render template: "notes/show"
    end
  end

  def destroy
    @book_mark_detail = BookMarkDetail.find(params[:id])
    @book_mark_detail.destroy
    redirect_to book_mark_path(@book_mark_detail.book_mark.id)
  end

  private

  def book_mark_detail_params
    params.require(:book_mark_detail).permit(:note_id, :book_mark_id)
  end
end

app/controllers/book_marks_controller.rb
class BookMarksController < ApplicationController
  before_action :private_url, only:[:show, :update]

  def index
    @book_mark = BookMark.new
    @book_marks = current_user.book_marks.page(params[:page]).per(8)
  end

  def create
    @book_mark = BookMark.new(book_mark_params)
    @book_mark.user_id = current_user.id
    if @book_mark.save
      redirect_to book_marks_path
    else
      @book_marks = current_user.book_marks.page(params[:page]).per(8)
      render :index
      @book_mark = BookMark.new
    end
  end

  def show
    @book_mark = BookMark.find(params[:id])
    @book_mark_details = @book_mark.book_mark_details
  end

  def update
    @book_mark = BookMark.find(params[:id])
    if @book_mark.update(book_mark_params)
      redirect_to book_mark_path(@book_mark.id)
    else
      @book_mark_details = @book_mark.book_mark_details
      render :show
    end
  end

  def destroy
    @bookmark = BookMark.find(params[:id])
    @bookmark.destroy
    redirect_to book_marks_path
  end

  private

  def private_url
    @book_mark = BookMark.find(params[:id])
    unless @book_mark.user_id == current_user.id
      redirect_to book_marks_path
    end
  end

  def book_mark_params
    params.require(:book_mark).permit(:name)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @note = Note.find(params[:note_id])
    @memo = current_user.memos.new(memo_params)
    @memo.note_id = @note.id
    if @memo.save
      redirect_to note_path(@note.id)
    else
      @memos = current_user.memos.all
      @book_marks = current_user.book_marks.all
      @book_mark_detail = BookMarkDetail.new
      render "notes/show"
      @memo = Memo.new
    end
  end

  def destroy
    @note = Note.find(params[:note_id])
    Memo.find(params[:id]).destroy
    redirect_to note_path(params[:note_id])
  end

  private

  def memo_params
    params.require(:memo).permit(:memo)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :private_url, only: [:show, :edit, :update]

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to note_path(@note.id)
    else
      render :new
    end
  end

  def index
    @notes = current_user.notes.page(params[:page]).per(8)
    @user = current_user
  end

  def show
    @note = Note.find(params[:id])
    @memo = Memo.new
    @memos = current_user.memos.all

    @book_marks = current_user.book_marks.all
    @book_mark_detail = BookMarkDetail.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to note_path(@note.id)
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path
  end

  private

  def private_url
    @note = Note.find(params[:id])
    unless @note.user_id == current_user.id
      redirect_to notes_path
    end
  end

  def note_params
    params.require(:note).permit(:opinion, :experience, :emotion, :value)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_mark_details_helper.rb
module BookMarkDetailsHelper
end

app/helpers/book_marks_helper.rb
module BookMarksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_marks/index.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-md-auto">
      <h2><strong>ブックマーク</strong></h2>
    </div>

    <div class="col-md-auto">
      <table>
        <tr>
          <td>
            <% if @book_mark.errors.any? %>
              <ul>
                <% @book_mark.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </td>
        </tr>
        <%= form_with model: @book_mark, url: book_marks_path, method: :post, local: true do |f| %>
        <tr>
          <td><%= f.text_field :name, class: "form-control" %></td>
          <td><%= f.submit "新規ブックマーク作成", class: "btn btn-outline-info" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row justify-content-md-center mt-3">
    <% @book_marks.each do |book_mark| %>
    <div class="col-md-4 m-5">
      <div class="card text-white bg-info">
        <%= book_mark.created_at.strftime('%Y/%m/%d') %><br>
        <h4><strong><%= link_to book_mark.name.truncate(8), book_mark_path(book_mark.id), class: "text-white stretched-link" %></strong></h4>
      </div>
      <%= link_to "削除", book_mark_path(book_mark.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger btn-sm mt-1" %>
    </div>
    <% end %>
  </div>

  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <%= paginate @book_marks %>
    </div>
  </div>
</div>

app/views/book_marks/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong><%= @book_mark.name %></strong></h2>
    </div>

    <%= form_with model: @book_mark, url: book_mark_path(@book_mark.id), method: :patch do |f| %>
    <div class="col">
      <table>
        <tr>
          <td>
            <% if @book_mark.errors.any? %>
              <ul>
                <% @book_mark.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </td>
        </tr>

        <tr>
          <td><%= f.text_field :name, class: "form-control" %></td>
          <td><%= f.submit "ブックマーク名変更", class: "btn btn-success" %></td>
        </tr>
      </table>
    </div>
    <% end %>
  </div>

  <div class="row mt-3">
    <div class="col">
      <table class="table">
        <thead class="table-info">
          <tr>
            <th>作成日</th>
            <th>意見</th>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% @book_mark_details.each do |book_mark_detail| %>
          <tr>
            <td><%= book_mark_detail.note.created_at.strftime('%Y/%m/%d %H') %></td>
            <td><%= link_to book_mark_detail.note.opinion.truncate(20), note_path(book_mark_detail.note.id) %></td>
            <td><%= link_to "ブックマークから外す", book_mark_detail_path(book_mark_detail.id), method: :delete, "data-confirm" => "ブックマークから外しますか？", class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-md-auto">
      <h1><strong>リフレクションノートについて</strong></h1>
    </div>
  </div>

  <div class="row justify-content-md-center mt-5">
    <div class="col-md-auto">
      <h3 class="text-center m-2">
        このサイトでは、事実や経験に対する自分（または他人）の判断や意見を
      </h3>
    </div>

    <div class="col-md-auto m-2">
      <h3 class="text-center text-primary">
        「意見」「経験」「感情」「価値観」
      </h3>
    </div>

    <div class="col-md-auto m-2">
      <h3 class="text-center">
        に切り分けて、可視化するためのノートを作成することができます。
      </h3>
    </div>

    <div class="col-md-auto m-5">
      <h3 class="text-center">それをすることで、これまで気づかなかった自分（または他人）の内側にある思考を、<u class="text-primary">他面的に、そしてより深く</u>知ることができるようになります。</h3>
    </div>

    <div class="col-md-auto m-3">
      <h3 class="text-center"><u class="text-success">自分の成長や、他人との円滑なコミュニケーションを図る</u>など、さまざまな場面で役立てることができるでしょう。</h3>
    </div>

    <div class="col-md-auto m-2">
      <h3 class="text-center">ぜひ活用してみてください。</h3>
    </div>
  </div>

  <div class="row justify-content-md-center mt-4">
    <div class="col-md-auto text-border">
      <p><u>参考:「リフレクション 自分とチームの成長を加速させる内省の技術」/ 著: 熊平美香</u></p>
    </div>
  </div>

</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row justify-content-md-center justify-content-sm-center mt-5">
    <div class="col-md-auto col-sm-auto">
      <h2><strong>リフレクション ノート</strong></h2>

      </div>
    </div>

    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <div class="btn-wrapper col-10 mx-auto mt-5">
          <div class="row">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary btn-md btn-block mb-3" %>
          </div>

          <div class="row">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-success btn-md btn-block mt-3" %>
          </div>

      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReflectionNote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm bg-info">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "ユーザー情報", user_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "ノート一覧", notes_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "ブックマーク", book_marks_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "About", about_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white m-2 navbar-brand" %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "Top", root_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "About", about_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "text-white m-2 navbar-brand" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "text-white m-2 navbar-brand" %>
              </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="bg-info text-white pt-5 bd-4">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <p>︎Reflection Note</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/notes/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ノート編集</strong></h2>
      <% if @note.errors.any? %>
        <ul>
          <% @note.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @note, url: note_path(@note.id), method: :patch do |f| %>
  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "意見", class: "form-label" %><br>
        <%= f.text_area :opinion, class: "form-control mb-3" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "経験", class: "form-label" %><br>
        <%= f.text_area :experience, class: "form-control mb-3" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "感情", class: "form-label" %><br>
        <%= f.text_area :emotion, class: "form-control mb-3" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "価値観", class: "form-label" %><br>
        <%= f.text_area :value, class: "form-control mb-3" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="actions">
        <%= link_to "戻る", :back, class: "btn btn-secondary mt-3" %>
        <%= f.submit "変更を保存", class: "btn btn-success mt-3" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/notes/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ノート一覧</strong></h2>
    </div>

    <div class="col">
      <ul>
        <li class="nav nav-item">
          <%= link_to "新規ノート作成", new_note_path, class: "btn btn-outline-info" %>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <h5 class="text-info"><u>ノート数：<%= @user.notes.count %></u></h5>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="table-info">
          <tr>
            <td>作成日</td>
            <td>意見</td>
            <td></td>
          </tr>
        </thead>

        <% @notes.each do |note| %>
        <tbody>
          <tr>
            <td><%= note.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to note.opinion.truncate(20), note_path(note.id) %></td>
            <td><%= link_to "削除", note_path(note.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <%= paginate @notes %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ノート作成</strong></h2>
      <% if @note.errors.any? %>
        <ul>
          <% @note.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @note, url: notes_path, method: :post do |f| %>
  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "意見", class: "label" %><br>
        <%= f.text_area :opinion, placeholder: "意見はなんですか？", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "経験", class: "label" %><br>
        <%= f.text_area :experience, placeholder: "その意見に基づく経験はなんですか？", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "感情", class: "label" %><br>
        <%= f.text_area :emotion, placeholder: "その経験はどんな感情を覚えましたか？", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "価値観", class: "label" %><br>
        <%= f.text_area :value, placeholder: "意見、経験、感情を踏まえてどんな価値観があると思いますか？", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="actions">
        <%= link_to "戻る", notes_path, class: "btn btn-secondary mt-3" %>
        <%= f.submit "登録", class: "btn btn-success mt-3" %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ノート詳細</strong></h2>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered">
        <tr>
          <th class="table-info">意見</th>
          <td><%= @note.opinion %></td>
        </tr>

        <tr>
          <th class="table-info">経験</th>
          <td><%= @note.experience %></td>
        </tr>

        <tr>
          <th class="table-info">感情</th>
          <td><%= @note.emotion %></td>
        </tr>

        <tr>
          <th class="table-info">価値観</th>
          <td><%= @note.value %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row justify-content-md-center mt-3">
    <div class="col-md-auto">
      <%= link_to "編集", edit_note_path(@note.id), class: "btn btn-outline-success" %>
    </div>

    <% if @book_marks.present? %>
    <div class="col-md-auto">
      <%= form_with model: @book_mark_detail, url: book_mark_details_path, method: :post do |f| %>
        <%= f.hidden_field :note_id, :value => @note.id %>
        <%= f.collection_select(:book_mark_id, @book_marks, :id, :name) %>
        <%= f.submit "ブックマークに追加", class: "btn btn-outline-info" %>
      <% end %>
    </div>

    <% else %>
    <div class="col">
      <%= link_to "ブックマークに追加", book_marks_path, class: "btn btn-outline-info" %>
    </div>

    <% end %>

  </div>

  <div class="row mt-5">
    <div class="col">
      <table class="table">
        <% @note.memos.each do |memo| %>
        <tr>
          <td><%= memo.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= memo.memo %></td>
          <td><%= link_to "削除", note_memo_path(memo.note, memo), method: :delete, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>


  <div class="row m-4">
    <div class="col">
      <div class="field">
        <% if @memo.errors.any? %>
        <ul>
          <% @memo.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
        <% end %>
        <%= form_with model: [@note,@memo] do |f| %>
          <%= f.text_field :memo, placeholder: "メモ", class: "form_control" %>
          <%= f.submit "メモ追加", class: "btn btn-outline-info btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ユーザー情報編集</strong></h2>
    </div>
  </div>
  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @user, url: user_path, method: :patch do |f| %>
  <div class="row mt-3">
    <div class="col">
      <div class="field">
        <%= f.label "ニックネーム", class: "form-label" %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="field">
        <%= f.label "メールアドレス", class: "form-label" %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <div class="actions">
        <%= link_to "戻る", user_path, class: "btn btn-secondary mt-1" %>
        <%= f.submit "変更を保存", class: "btn btn-success mt-1" %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2><strong>ユーザー情報</strong></h2>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered">
        <tr>
          <th class="table-info">登録日</th>
          <td><%= @user.created_at.strftime('%Y/%m/%d') %></td>
        </tr>

        <tr>
          <th class="table-info">ニックネーム</th>
          <td><%= @user.name %></td>
        </tr>

        <tr>
          <th class="table-info">メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>

        <tr>
          <th class="table-info">ノート数</th>
          <td><%= @user.notes.count %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= link_to "編集", edit_user_path, class: "btn btn-outline-success" %>
    </div>
  </div>
</div>